spring:
  aop:
    proxy-target-class: true

server:
  port: 8081
  session:
    cookie:
      name: spring-cloud-user-web

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: spring-cloud-user-web
      client-secret: 123456
      access-token-uri: http://localhost:8088/oauth/token
      user-authorization-uri: http://localhost:8088/oauth/authorize
    resource:
      token-info-uri: http://localhost:8088/oauth/check_token
      user-info-uri: http://localhost:8088/user

---
spring:
  zipkin:
    base-url: http://localhost:9411