server:
  port: 9411

---
zipkin:
  storage:
    type: mysql

---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    default-auto-commit: true
    initial-size: 2
    max-active: 20
    min-idle: 1
    max-idle: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    remove-abandoned: true
    remove-abandoned-timeout: 180
    connection-properties: clientEncoding=UTF-8

---
eureka:
  client:
    serviceUrl:
          defaultZone: http://eureka.dev.com:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

---
spring:
  cloud:
    stream:
      bindings:
        sleuth:
          consumer:
            concurrency: 3
      kafka:
        binder:
          zk-nodes: 47.90.2.202:2181